### PR TITLE
Gcc 10

### PR DESCRIPTION
**Pull request by olerem**

### CODE REVIEW

**Comment by mimi89999** [comment]
Debian 11 Bullseye will include GCC 10 instead of GCC 8 that is in current stable. It will also have updated binutils. The firmware package was removed from testing because it doesn't build with current build tools: https://tracker.debian.org/news/1116514/open-ath9k-htc-firmware-removed-from-testing/

**Comment by erikarn** [comment]
> Debian 11 Bullseye will include GCC 10 instead of GCC 8 that is in current stable. It will also have updated binutils. The firmware package was removed from testing because it doesn't build with current build tools: https://tracker.debian.org/news/1116514/open-ath9k-htc-firmware-removed-from-testing/

merged!

**Comment by mimi89999** [comment]
@olerem Could you please update the package and reupload it to Debian?

**Comment by olerem** [comment]
@mimi89999 , no  I can't maintain debian package. I just do not have enough tome for it.

**Comment by jscott0** [comment]
@mimi89999 I'm adopting the firmware-ath9k-htc Debian package from @olerem. With his patches it's on GCC 10 and Binutils 2.34. It's in very good shape, an upload is imminent, and I'm talking to the kernel team about getting it into the installer in time. Things are looking good :)
https://mentors.debian.net/package/open-ath9k-htc-firmware/

**Comment by erikarn** [comment]
Thanks!


-a

**Pull request merged**
