### PR TITLE
Fix license missed during initial conversion

### PR DESCRIPTION
**Pull request by kpengboy**
Requested by Adrian Chadd in #45

### CODE REVIEW

**Comment by Legimet** [comment]
This has been open for almost a year. All that needs to be done is:
* Update the license of target_firmware/wlan/ah_osdep.h to add "with or without modification"
* Fix the license in NOTICE.TXT
* Fix the license in LICENCE.open-ath9k-htc-firmware in linux-firmware.git

**Comment by erikarn** [comment]
Sorry, I missed this! Lots of life changes, etc.

Committed!

**Comment by Legimet** [comment]
That was quick! Thanks.

**Comment by erikarn** [comment]
Welcome to what it's like poking adrian to do things. Just poke adrian to
do things. :)



-a

**Pull request merged**
